server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

jwt:
  signerKey: "LIQM/m8NKaFF7nZBdJsSkTh4YU4EBB9S5p/aQ1Zbt/Hg7VPXY0Idae42bXom6Kx1"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second